config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :clients do
    resources :transactions
    resources :cases do
      resources :collections
    end
  end

  get 'clients/:client_id/case_options', to: 'transactions#case_options'

  root 'clients#new'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :case

  validates :amount, presence: true
  validates :description, presence: true

  def calculation_amount(selected_ratio)
    case selected_ratio
    when '9,1%'
      amount * 9.1 / 100
    when '4,55%'
      amount * 4.55 / 100
    when '2,7%'
      amount * 2.7 / 100
    when 'none'
      amount
    else
      amount
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_case, only: %i[new create]

  def index
    @collections = Collection.all
  end

  def new
    @collection = @case.collections.build
  end

  def show
    @collection = Collection.find(params[:id])
    @case = @collection.case
    @client = @case&.client

    render json: @collection
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  rescue => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def create
    @collection = @case.collections.build(collection_params)
    if @collection.save
      redirect_to client_case_path(@case.client, @case)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def set_case
    @case = Case.find(params[:case_id])
  end

  def collection_params
    params.require(:collection).permit(:date, :description, :amount)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/new.html.erb
<div class="wrapper-collection">
  <div class="wrapper">
    <div class="header-collection">
      <h3>New Collection</h3>
    </div>
    <div class="form-collection">
      <%= form_with(model: [@case, @collection],local: true, url: client_case_collections_path(@case.client, @case)) do |form| %>
        <div class="field mt-3">
          <%= form.label :amount %>
          <%= form.text_field :amount, class: 'form-control' %>
        </div>

        <div class="field mt-3">
          <%= form.label :description %>
          <%= form.text_area :description %>
        </div>

        <div class="field mt-3">
          <%= form.label :date %>
          <%= form.date_field :date %>
        </div>

        <div class="submit-button mt-3">
          <%= form.submit 'Create Collection' %>
        </div>
      <% end %>
    </div>
  </div>
</div>