config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :clients do
    resources :transactions
    resources :cases do
      resources :collections
    end
  end

  get 'clients/:client_id/case_options', to: 'transactions#case_options'

  root 'clients#new'
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_client, only: %i[new create]

  def new
    @case = @client.cases.new
  end

  def index
    if params[:client_id].present?
      @client = Client.find(params[:client_id])
      @cases = @client.cases
    else
      @cases = Case.all
    end
  end

  def create
    @case = @client.cases.new(case_params)
    if @case.save
      respond_to do |format|
        format.turbo_stream { redirect_to client_cases_path }
        format.html { redirect_to client_cases_path }
      end
    else
      format.turbo_stream { render turbo_stream: turbo_stream.replace('form-errors', partial: 'shared/form_errors', locals: { resource: @cases }) }
      format.html { render 'new', status: :unprocessable_entity }
    end
  end

  def show
    @case = Case.find(params[:id])
    @collections = @case.collections
    @client = @case.client
    @transactions = @case.transactions
  end

  def edit
    @case = Case.find(params[:id])
  end

  def update
    @case = Case.find(params[:id])
    @client = @case.client
    if @case.update(case_params)
      redirect_to client_path(@case)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @case = Case.find(params[:id])
    @client = @case.client
    @case.destroy
    redirect_to client_path(@client), status: :see_other
  end

  private

  def set_client
    @client = Client.find(params[:client_id])
  end

  def case_params
    params.require(:case).permit(:court, :court_number, :client_id)
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/create.turbo_stream.erb
<%= turbo_stream.append "transaction_case_id", @case %>

app/views/cases/index.html.erb
<h3>Find me on app/views/cases/index.html.erb</h3>

<div class="case-table-title">
  <p>Case List for <%= @client.last_name %>, <%= @client.first_name %></p>
</div>
<div class="case-table mt-3">
  <table>
    <thead>
      <tr>
        <th>Court</th>
        <th>Court Number</th>
      </tr>
    </thead>
    <tbody>
      <% @cases.each do |individual_case| %>
        <tr>
          <td><%= individual_case.court%></td>
          <td><%= individual_case.court_number %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="button-r mt-3">
  <%= link_to 'Back', clients_path %>
</div>

<div class="button-b mt-5">
  <%= link_to "Create new case", new_client_case_path %>
</div>

app/views/cases/new.html.erb
<div class="wrapper-case">
  <div class="wrapper">
    <div class="header-case">
      <h3>New Case</h3>
    </div>
    <div class="form-case">
      <%= form_with(model: [@client, @case],local: true) do |form| %>
        <div class="field mt-3">
          <%= form.label :court %>
          <%= form.text_field :court, class: 'form-control' %>
        </div>
        <div class="field mt-3">
          <%= form.label :court_number %>
          <%= form.text_field :court_number, class: 'form-control' %>
        </div>
        <div class="submit-button mt-3">
          <%= form.submit 'Create Case' %>
        </div>
      <% end %>
    </div>
    <div class="button mt-3">
      <%= link_to "Case List", client_cases_path %>
    </div>
  </div>
</div>

app/views/cases/show.html.erb
<h3>Find me on app/views/cases/show.html.erb</h3>

<h1>Case Details</h1>
<p><strong>Court:</strong> <%= @case.court %></p>
<p><strong>Court Number:</strong> <%= @case.court_number %></p>
<p><strong>Client:</strong> <%= @case.client.last_name %></p>

<div class="mt-5">
  <p style="font-weight: bold; margin-left:25px">Collections</p>

  <div class="d-menu">
    <%= select_tag "selected_collection", options_from_collection_for_select(@collections, 'id', 'description'), prompt: 'Select a collection', data: { controller: 'collection', action: 'change->collection#updateTable', client_id: @client.id, case_id: @case.id, collection_target: 'selection'} %>
  </div>
  <div class="collection-table mt-3">
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Amount <i class="fa-solid fa-turkish-lira-sign fa-xs"></th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% @collections.each do |collection| %>
          <tr>
            <td><%= collection.date.strftime('%b %d, %Y') if collection.date %></td>
            <td><%= collection.amount %></td>
            <td><%= collection.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="button-b mt-3">
  <%= link_to "Create Collection", new_client_case_collection_path(case_id: @case.id)  %>
</div>

<div class="button-r mt-3">
  <%= link_to "Back to Client", client_path(@case.client) %>
</div>

<div class="collection-title" data-collection-target="collectionTitle" >
  <p></p>
</div>

<div class="collection-calculation-table" data-collection-target="collectionTable" data-controller="collection" data-client-id="<%= @client.id %>" data-case-id="<%= @case.id %>">
  <table>
    <thead>
      <tr>
        <th>Transaction Party</th>
        <th>Details</th>
        <th>Ratio</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>


<div class="expense-detail mt-3">Expenses: <span id="totalAmount"></span></div>
<div class="expense-detail mt-3">Amount to be sent to the client: <span id="amountToBeSentToClient"></span></div>


<button id="printButton">Print Table</button>

<div class="case-expense-table mt-3">
  <h4>Expenses Related to case</h4>
  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>Description</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @case.transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.amount %></td>
          <td><%= transaction.description %></td>
          <td><%= transaction.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>