config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :clients do
    resources :transactions
    resources :cases do
      resources :collections
    end
  end

  get 'clients/:client_id/case_options', to: 'transactions#case_options'

  root 'clients#new'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :transactions, dependent: :destroy
  has_many :cases, dependent: :destroy
  has_many :collections, through: :cases

  validates :first_name, presence: true
  validates :last_name, presence: true

  include PgSearch::Model
  multisearchable against: %i[first_name last_name]

  def balance
    total_payments = transactions.where(transaction_type: 'payment').sum(:amount)
    total_expenses = transactions.where(transaction_type: 'expense').sum(:amount)
    total_payments - total_expenses
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  def new
    @client = Client.new
  end

  def index
    @clients = Client.all

    if params[:query].present?
      sql_query = 'first_name ILIKE :query OR last_name ILIKE :query'
      @clients = Client.where(sql_query, query: "%#{params[:query]}%")
    else
      @clients = Client.all
    end
  end

  def show
    @transactions = @client.transactions
    @expenses = @transactions.where(transaction_type: 'expense')
    @payments = @transactions.where(transaction_type: 'payment')
    @collections = @client.cases.flat_map(&:collections)
  end

  def create
    @client = Client.new(client_params)

    if @client.save

      redirect_to clients_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @client.update(client_params)
      redirect_to client_path
    else
      render edit
    end
  end

  def destroy
    @client.destroy

    redirect_to clients_path, status: :see_other
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:first_name, :last_name)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<div class="wrapper-client-edit">
  <div class="wrapper">
    <div class="header-client">
      <h3>Edit Client</h3>
    </div>
    <div class="form-client">
      <%= form_with(model: @client, url: client_path(@client), method: :patch) do |form| %>
        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="submit-button mt-3">
          <%= form.submit 'Edit Client' %>
        </div>
      <% end %>
    </div>
    <div class="button mt-3">
      <%= link_to 'Back', client_path(@client) %>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="card-container">
  <p>Number of Clients:</p>
  <div class="card-info">
    <p>#<%= @clients.count %></p>
  </div>
</div>

<div class="search-container mb-5">
  <%= form_with url: clients_path, method: :get, class:"d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a client..."
    %>
    <%= submit_tag "Search", class:"btn-s" %>
  <% end %>
</div>

<div class="index-table">
  <table>
    <thead>
      <tr>
        <th>Client Name</th>
        <th>Advance Payment</th>
        <th>Expenses</th>
        <th>Detail <i class="fa-solid fa-magnifying-glass"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @clients.sort_by { |client| [client.last_name, client.first_name] }.each_with_index do |client, index| %>
        <tr class="<%= index.odd? ? 'odd-row' : 'even-row' %>">
          <td><%= client.last_name %>, <%= client.first_name %></td>
          <td><%= client.transactions.where(transaction_type: 'payment').sum(:amount) %></td>
          <td><%= client.transactions.where(transaction_type: 'expense').sum(:amount) %></td>
          <td>
            <%= link_to "Review", client %>
            <%= link_to "", client_cases_path(client_id: client.id), class:"fa-regular fa-folder-open" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>




<div class="button-b mt-5">
  <%= link_to "Create new client", new_client_path %>
</div>

app/views/clients/new.html.erb
<div class="wrapper-client">
  <div class="wrapper">
    <div class="header-client">
      <h3>New Client</h3>
    </div>
    <div class="form-client">
      <%= form_with(model: @client, url: clients_path, method: :post) do |form| %>
        <div class="field mt-3">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="field mt-3">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="submit-button mt-3">
          <%= form.submit 'Create Client' %>
        </div>
      <% end %>
    </div>
    <div class="button mt-3">
      <%= link_to "Clients List", clients_path %>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<h4 style="margin-top:25px; margin-left:25px;">Calculation for <%= @client.last_name %>, <%= @client.first_name %></h4>
<div class="show-page-container">
  <div class="left-card">
    <div class="date-div">
      <%= Date.today %> <i class="fa-regular fa-calendar-days"></i>
    </div>

    <div class="<%=(@payments.sum(:amount) - @expenses.sum(:amount)).negative? ? 'neg-show-card-container' : (@payments.sum(:amount) - @expenses.sum(:amount)).zero? ? 'zero-show-card-container' : 'pos-show-card-container' %>">
      <div class=" show-card-info">
        <p class="info-line-one"><%= @client.first_name %> <%= @client.last_name %></p>
        <p class="info-line-two"> 4756 .... .... 0098</p>
      </div>
      <div class="show-card-detail">
        <p>Balance <i class="fa-solid fa-coins"></i> <%= (@payments.sum(:amount) - @expenses.sum(:amount)) %> <i class="fa-solid fa-turkish-lira-sign fa-xs"></i> </p>
        <div class= "detail-icon">
          <i class="fa-regular fa-paper-plane fa-xs"></i>
          <i class="fa-solid fa-arrow-down fa-xs"></i>
        </div>
      </div>
    </div>

    <div class="calculation-container mt-5">
      <div class="expense-card">
        <p>Total Expenses <i class="fa-regular fa-paper-plane"></i></p>
        <p><%= @expenses.sum(:amount) %> <i class="fa-solid fa-turkish-lira-sign fa-xs"></i></p>
      </div>
      <div class="payment-card">
        <p>Total Payments <i class="fa-solid fa-arrow-down"></i></p>
        <p><%= @payments.sum(:amount) %> <i class="fa-solid fa-turkish-lira-sign fa-xs"></i></p>
      </div>
    </div>

    <div class="button-group mt-5 mb-5">
      <%= link_to "", clients_path, class:"fa-solid fa-arrow-left btn btn-primary " %>
      <%= button_to "", @client, method: :delete, data: {turbo_confirm: "Are you sure you want to delete this client?"}, class:"fa-solid fa-ban btn btn-danger" %>
      <%= link_to "", edit_client_path,  class: "fa-solid fa-user-pen btn btn-warning " %>
    </div>

    <div class="button-t">
      <%= link_to "Create Transaction", new_client_transaction_path(@client) %>
    </div>
  </div>

  <div class="right-card">
    <h4>Transaction History for <%= @client.last_name %>, <%= @client.first_name %></h4>
    <div class="table-card">
      <p>Expenses</p>
      <div class="expense-table mt-3">
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Amount <i class="fa-solid fa-turkish-lira-sign fa-xs"></th>
              <th>Type</th>
              <th>Description</th>
              <th>Case Info</th>
              <th>Actions</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.sort_by(&:date).reverse.each do |transaction| %>
              <% if transaction.transaction_type == 'expense' %>
                <tr>
                  <td><%= transaction.date.strftime('%b %d, %Y') %></td>
                  <td><%= transaction.amount %></td>
                  <td style="color:#bb2d3b"><%= transaction.transaction_type %></td>
                  <td><%= transaction.description %></td>
                  <% transaction.transaction_cases.each do |transaction_case| %>
                    <% case_record = transaction_case.case %>
                    <td class="case-link"><%= link_to "#{case_record&.court}- #{case_record&.court_number}", client_case_path(@client, case_record) %></td>
                  <% end %>

                  <td><%= button_to "", client_transaction_path(@client, transaction), class: "fa-regular fa-trash-can",
                                    method: :delete, data: { turbo_confirm: "Are you sure you want to delete this transaction?" } %></td>
                  <td><%= link_to "", edit_client_transaction_path(@client, transaction), class:"fa-regular fa-pen-to-square" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="mt-5">
        <p style="font-weight: bold">Payments</p>
        <div class="payment-table mt-3">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Amount <i class="fa-solid fa-turkish-lira-sign fa-xs"></th>
                <th>Type</th>
                <th>Description</th>
                <th>Actions</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @transactions.sort_by(&:date).reverse.each do |transaction| %>
                <% if transaction.transaction_type == 'payment' %>
                  <tr>
                    <td><%= transaction.date.strftime('%b %d, %Y') %></td>
                    <td><%= transaction.amount %></td>
                    <td style="color:#198754"><%= transaction.transaction_type %></td>
                    <td><%= transaction.description %></td>

                    <td style="padding: 0"><%= button_to "", client_transaction_path(@client, transaction), class: "fa-regular fa-trash-can",
                                      method: :delete, data: { turbo_confirm: "Are you sure you want to delete this transaction?" } %></td>
                    <td><%= link_to "", edit_client_transaction_path(@client, transaction), class:"fa-regular fa-pen-to-square"%></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>